name: Práticas DevOps - Deploy PWA

on:
  push:
    branches: [ main ] 

permissions:
  contents: write 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
     
    - name: checkout-codigo
      uses: actions/checkout@v4

    - name: Valida a estrutura do PWA
      run: |
        echo "Iniciando validação de arquivos obrigatórios para a aula..."
        test -f index.html && echo "✓ index.html encontrado no sistema" || (echo "✗ Erro: index.html está ausente" && exit 1)
        test -f manifest.json && echo "✓ manifest.json encontrado no sistema" || (echo "✗ Erro: manifest.json está ausente" && exit 1)
        test -f sw.js && echo "✓ sw.js encontrado no sistema" || (echo "✗ Erro: sw.js está ausente" && exit 1)

    - name: Deploy do projeto no GitHub Pages 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: . 
        branch: gh-pages 